name: Employee Manager CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    env:
      DATABASE_NAME: EmployeeManager
      DATABASE_USER: root
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: employee_db
      DATABASE_PORT: 3306

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: EmployeeManager
        ports:
          - 3306

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        (cd EmployeeManager; python manage.py test)
